#!/bin/bash

# install fzf rbenv ruby-build
# automate ctrl to caps rebind
# map f1 to escape somehow

sudo add-apt-repo ppa:git-core/ppa
sudo apt-get update
sudo apt-get install mc gnome-commander git vim zsh htop kupfer libgnutls-dev build-essential cmake libuuid1 libuu-dev libuu0 uuid-dev 
curl -O http://taskwarrior.org/download/taskd-latest.tar.gz
tar xzf taskd-latest.tar.gz
 

