git subtree pull --prefix .vim/bundle/nerdtree https://github.com/scrooloose/nerdtree.git  --squash master
git subtree pull --prefix .vim/bundle/syntastic https://github.com/scrooloose/syntastic.git --squash master 
git subtree pull --prefix .vim/bundle/vim-fugitive https://github.com/tpope/vim-fugitive.git  --squash master
git subtree pull --prefix .vim/bundle/gitgutter https://github.com/jisaacks/GitGutter.git --squash master
git subtree pull --prefix .vim/bundle/vim-markdown https://github.com/plasticboy/vim-markdown.git --squash master
git subtree pull --prefix .vim/bundle/vim-markdown-preview https://github.com/JamshedVesuna/vim-markdown-preview.git --squash master
git subtree pull --prefix .vim/bundle/vim-rsi https://github.com/tpope/vim-rsi.git --squash master
git subtree pull --prefix .vim/bundle/vim-surround https://github.com/tpope/vim-surround.git --squash master
git subtree pull --prefix .vim/bundle/ack-vim https://github.com/mileszs/ack.vim.git --squash master
git subtree pull --prefix .vim/bundle/ctrlp https://github.com/ctrlpvim/ctrlp.vim.git --squash master
git subtree pull --prefix .vim/bundle/command-t https://github.com/wincent/command-t.git --squash master
git subtree pull --prefix .vim/bundle/vim-bracketed-paste https://github.com/ConradIrwin/vim-bracketed-paste.git --squash master
git subtree pull --prefix .vim/bundle/vim-unimpaired https://github.com/tpope/vim-unimpaired.git --squash master
git subtree pull --prefix .vim/bundle/vim-sensible https://github.com/tpope/vim-sensible.git --squash master
git subtree pull --prefix .vim/bundle/vim-commentary https://github.com/tpope/vim-commentary.git --squash master
git subtree pull --prefix .vim/bundle/vim-repeat https://github.com/tpope/vim-repeat.git --squash master
git subtree pull --prefix .vim/bundle/vim-tbone https://github.com/tpope/vim-tbone.git --squash master
